---
title: "Public Art Map Portland"
author: "Winston Saunders"
date: "May 31, 2015"
output: html_document
---

To get the data use the following function. The data are stored in my GitHub.

```{r "get data", echo=9:13}        
        ## define a read_data function which will be used to pull data from my gitbhub acct
        ## 
        library(RCurl)
        readData <- function(path.name, file.name, column.types, missing.types) {
                ## create URL from path and file names
                myData<-getURL(paste0(path.name, file.name) )
                ## read the data
                read.csv(textConnection(myData),
                colClasses=column.types,
                na.strings=missing.types )
                
            }

```

The variables for the function are defined as below. 
The train.column.types simplifies the data cleaning for the analysis.

```{r, echo=FALSE, warning=FALSE}

        file.path <- "https://raw.githubusercontent.com/ww44ss/public_art/master/"
        data.file <- "public_art_edited.csv"
        data.zip <- "public_art.zip"
        missing.types <- c("NA", "")

        column.types <- c('integer',   # record_id
                                'factor',    # artist 
                                'factor',    # title
                                'factor',    # date
                                'character',       # medium
                                'character',       # discipline
                                'character',    # dimensions
                                'factor',     # funding_source
                                'character',    # location
                                'character',    # street
                                'factor',    # city
                                'factor',        #state
                                'factor',    # zipcode
                                "numeric",      # latitude
                                "numeric",      # longitude
                                "character",    # description
                                "character",    # image URL
                                "character",    # detail URL
                                "factor"     # date_modified
        )

    
```

Now we can get the data quickly

```{r, echo=3:7}
        ##Okay let's get the data
        art <- readData(file.path, data.file, column.types, missing.types)
        
```

```{r "data cleaning", echo=FALSE}
## we have a few fields to clean up a bit
##
## Year
## inspection shows column contains mostly years, but let's just polish it up a bit. 

        year_clean<-function(x) {
                        x<-gsub("20th century", "1975", x)      ## approximate year
                        x<-gsub("19th century", "1875", x)      ## approximate year
                        x<-gsub("18th century", "1775", x)      ## approximate year
                        x<-sub("0.9994979", "1999", x)          ## fix this line with correct date
                        x<-gsub(" ", "", x)                     ## eliminate spaces
                        x<-gsub('[[:alpha:]]+', "", x)          ## get rid of letters
                        x<-gsub("[[:punct:]]+", "", x)          ## eliminate punctuation marks
                        x<-substring(x, 1, 4)                   ## keep first 4 digits as year
                        return(x)
                         }



    art$year<-as.numeric(year_clean(art$date))  ## clean and convert to integer

```

```{r}

require(ggmap)
require(mapproj)

##Subset data by crime
## here focus on only top crimes
        ##get map data
        map <- get_map(source="google", maptype="roadmap", location = 'Portland', zoom = 11)
        ##generate map
        map1 <- ggmap(map) 

        ## 
        map1<-map1 + geom_point(aes(x = art$lng, y = art$lat), data = art, alpha = .5, color="red", size = 3)
        print(map1)

```

A more detailed zoom of downtown

```{r}

require(ggmap)
require(mapproj)

##Subset data by crime
## here focus on only top crimes
        ##get map data
        map <- get_map(source="google", maptype="roadmap", location = 'Portland', zoom = 15)
        ##generate map
        map1 <- ggmap(map) 

        ## 
        map1<-map1 + geom_point(aes(x = art$lng, y = art$lat), data = art, alpha = .5, color="red", size = 3)
        print(map1)

```